name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
  
  tsr:
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run tsr:check
  
  ts-prune:
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run ts-prune 